/*
 *  ledfont.c
 *  Nolleblink 2010 | Blinkmojt
 *
 *  Modified by Fredrik Ahlberg on 2010-06-25.
 *  Original implementation by Joakim Arnsby.
 *  Copyright (c) 2009 - 2010 ETF. All rights reserved.
 *
 */

#include "ledfont.h"

/* PURE EVIL OF DOOOM! */
#define X )<<1|1
#define _ )<<1
#define s ((((((((0

const unsigned char smallfont[255*5] =
{
  s _ _ _ _ _ _ _ _,
  s _ _ _ _ _ _ _ _,
  s _ _ _ _ _ _ _ _,
  s _ _ _ _ _ _ _ _,
  s _ _ _ _ _ _ _ _,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X X X _ _ ,
  s _ _ X _ X _ X _ ,
  s _ X _ _ X _ _ X ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ X X X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X X X _ _ ,
  
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X X X _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ _ X _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ X _ _ ,

  s _ _ _ X _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ X _ _ _ _ _ ,
  s _ _ _ X _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ X X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ X X ,
  s _ _ _ _ _ _ _ _ ,
  //36
  s _ _ _ X _ X _ _ ,
  s _ X X X X X X X ,
  s _ _ _ X _ X _ _ ,
  s _ X X X X X X X ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ _ _ X _ _ ,
  s _ _ X _ X _ X _ ,
  s _ X X X X X X X ,
  s _ _ X _ X _ X _ ,
  s _ _ _ X _ _ _ _ ,

  s _ _ X _ _ _ X X ,
  s _ _ _ X _ _ X X ,
  s _ _ _ _ X _ _ _ ,
  s _ X X _ _ X _ _ ,
  s _ X X _ _ _ X _ ,

  s _ _ X X _ X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ X _ X _ X ,
  s _ _ X _ _ _ X _ ,
  s _ X _ X _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ X X ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ X X X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X X X _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ X X X X X _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ X X X X X _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X _ X _ _ _ _ ,
  s _ _ X X _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X X _ _ _ _ _ ,
  s _ X X _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ X _ _ _ _ _ _ ,
  s _ _ X X _ _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X X _ ,
  s _ _ _ _ _ _ _ X ,

  s _ _ X X X X X _ ,
  s _ X _ X _ _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ _ X _ X ,
  s _ _ X X X X X _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ X X X X X X X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ X _ _ _ _ X _ ,
  s _ X X _ _ _ _ X ,
  s _ X _ X _ _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ _ X X _ ,

  s _ _ X _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ X _ X X ,
  s _ _ X X _ _ _ X ,

  s _ _ _ X X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ _ X _ ,
  s _ X X X X X X X ,
  s _ _ _ X _ _ _ _ ,

  s _ _ X _ _ X X X ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X _ X ,
  s _ _ X X X _ _ X ,

  s _ _ X X X X _ _ ,
  s _ X _ _ X _ X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ _ X X _ _ _ _ ,

  s _ _ _ _ _ _ _ X ,
  s _ X X X _ _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ X _ X ,
  s _ _ _ _ _ _ X X ,

  s _ _ X X _ X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ _ X X _ X X _ ,

  s _ _ _ _ _ X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ _ X _ X _ _ X ,
  s _ _ _ X X X X _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ X X _ X X _ ,
  s _ _ X X _ X X _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ X _ X X _ ,
  s _ _ X X _ X X _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ X ,
  s _ X _ X _ _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ X X _ ,

  s _ _ X X X X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ X _ X _ X ,
  s _ X _ X X X X _ ,

  s _ X X X X X X _ ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ X X X X X X _ ,

  s _ X X X X X X X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ _ X X _ X X _ ,

  s _ _ X X X X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,

  s _ X X X X X X X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X X X _ _ ,

  s _ X X X X X X X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ _ _ _ X ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ _ _ X ,

  s _ _ X X X X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X X X X _ X _ ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X X X X X ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ X X X X X X X ,
  s _ X _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X X X X X X ,
  s _ _ _ _ _ _ _ X ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X _ _ _ _ _ X ,

  s _ X X X X X X X ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,

  s _ X X X X X X X ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ X X _ _ ,
  s _ _ _ _ _ _ X _ ,
  s _ X X X X X X X ,

  s _ X X X X X X X ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ _ _ _ ,
  s _ X X X X X X X ,

  s _ _ X X X X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ X X X X X _ ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ X X _ ,

  s _ _ X X X X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ X _ _ _ X ,
  s _ _ X _ _ _ _ X ,
  s _ X _ X X X X _ ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ X X _ _ X ,
  s _ _ X _ X _ _ X ,
  s _ X _ _ _ X X _ ,

  s _ X _ _ _ X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ _ X X _ _ _ X ,

  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,

  s _ _ X X X X X X ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X X X X X ,

  s _ _ _ X X X X X ,
  s _ _ X _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ _ _ X X X X X ,

  s _ _ X X X X X X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X X _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X X X X X ,

  s _ X X _ _ _ X X ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ X X _ _ _ X X ,

  s _ _ _ _ _ X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X _ _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X X X ,

  s _ X X _ _ _ _ X ,
  s _ X _ X _ _ _ X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ _ X X ,

  s _ X X X X X X X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,

  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ X X _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ X X _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,

  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X X X X X X X ,

  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ X _ _ ,

  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ X X X X X X X ,
  s _ X _ _ X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X _ _ _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ X _ _ _ ,
  s _ X X X X X X X ,

  s _ _ X X X _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ _ _ X X _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ X X X X X X _ ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ X _ ,

  s _ _ _ _ X X _ _ ,
  s _ X _ X _ _ X _ ,
  s _ X _ X _ _ X _ ,
  s _ X _ X _ _ X _ ,
  s _ _ X X X X X _ ,

  s _ X X X X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X X X X X _ X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X X X X _ X ,
  s _ _ _ _ _ _ _ _ ,

  s _ X X X X X X X ,
  s _ _ _ X _ _ _ _ ,
  s _ _ X _ X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ X X X X X X X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ X X X X X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ X X _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ X X X X X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X X X _ _ _ ,

  s _ X X X X X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X X _ _ _ ,
  s _ X X X X X _ _ ,

  s _ X X X X X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X _ _ X _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ _ X _ _ _ _ _ ,

  s _ _ _ _ _ X _ _ ,
  s _ _ X X X X X X ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ X X X X X _ _ ,

  s _ _ _ X X X _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ _ _ X X X _ _ ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X X X _ _ ,

  s _ X _ _ _ X _ _ ,
  s _ _ X _ X _ _ _ ,
  s _ _ _ X _ _ _ _ ,
  s _ _ X _ X _ _ _ ,
  s _ X _ _ _ X _ _ ,

  s _ _ _ _ X X _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ _ X X X X _ _ ,

  s _ X _ _ _ X _ _ ,
  s _ X X _ _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ _ X X _ _ ,
  s _ X _ _ _ X _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ X X _ X X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ X X _ X X _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ X _ _ _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ _ _ X X X X _ ,
  s _ _ X _ _ _ _ X ,
  s _ _ X _ _ _ _ X ,
  s _ X X _ _ _ _ X ,
  s _ _ _ X _ _ X _ ,

  s _ _ X X X X _ X ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ X X X X X _ X ,

  s _ _ X X X _ _ _ ,
  s _ X _ X _ X X _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ _ _ X X _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X X _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X X _ ,
  s _ X X X X _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X X X X _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X X X X _ X _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ _ _ X X _ _ _ ,
  s _ _ X _ _ X _ _ ,
  s _ _ X _ _ X _ _ ,
  s _ X X _ _ X _ _ ,
  s _ _ X _ _ X _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ X _ X X _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X X _ ,
  s _ _ _ X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ _ _ X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X X _ ,
  s _ _ _ X X _ _ _ ,

  s _ _ _ _ _ _ _ X ,
  s _ X _ _ _ X _ _ ,
  s _ X X X X X _ X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ X _ X _ ,
  s _ X X X X _ _ X ,
  s _ X _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ X _ _ _ ,
  s _ X X X X _ _ X ,
  s _ X _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ X ,
  s _ X X X X _ _ _ ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ X X X X X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X X _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X _ _ ,

  s _ _ X _ _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X X X X X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ _ X _ _ _ ,

  s _ X X X X X _ _ ,
  s _ _ _ _ X _ X _ ,
  s _ X X X X X X X ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ _ X ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X X _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X X _ ,
  s _ _ X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ X ,
  s _ _ X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X X _ ,
  s _ _ X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ X X X X _ _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ X X X X _ _ _ ,

  s _ _ _ _ X X _ _ ,
  s _ X _ X _ _ _ X ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ X ,
  s _ _ X X X X _ _ ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ X X ,
  s _ X _ _ _ _ X _ ,
  s _ X _ _ _ _ X X ,
  s _ _ X X X X _ _ ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ X ,
  s _ _ X X X X _ _ ,

  s _ X _ X X _ _ _ ,
  s _ _ X _ _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ _ X _ _ _ ,
  s _ _ X X _ X _ _ ,

  s _ X X _ X _ _ _ ,
  s _ X _ X X X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ X _ ,

  s _ X _ X X X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X _ X X _ X _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X X X _ X _ ,

  s _ _ X _ _ _ X _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ _ _ X _ ,

  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X X X X X _ ,
  s _ _ _ _ _ X _ X ,
  s _ _ _ _ _ _ _ X ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X X _ ,
  s _ X X X X _ _ X ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X X X X X _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ X ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X X _ ,
  s _ _ X X X _ _ X ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X X X X X _ X ,

  s _ X X X X X X _ ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ _ _ X X _ ,
  s _ _ _ _ _ X _ X ,
  s _ X X X X _ _ _ ,

  s _ X X X X X X _ ,
  s _ _ _ _ X _ _ X ,
  s _ _ _ X _ _ X _ ,
  s _ _ X _ _ _ _ X ,
  s _ X X X X X _ _ ,

  s _ _ _ X _ _ X _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X X X ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ X _ _ X _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ _ X _ ,
  s _ _ _ X _ _ _ _ ,

  s _ _ X X _ _ _ _ ,
  s _ X _ _ X _ _ _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,

  s _ _ X X X X X _ ,
  s _ X X X X X _ X ,
  s _ X _ X _ X _ X ,
  s _ X X _ X _ _ X ,
  s _ _ X X X X X _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X X _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X X _ X _ X _ ,
  s _ X _ X _ _ _ X ,

  s _ _ _ X _ X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ X X _ X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X X X _ _ _ X ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X _ X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ X _ X _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ _ _ X _ ,

  s _ _ X _ _ _ X _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ X _ X _ X _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X _ _ X _ _ X ,
  s _ _ X _ _ X _ _ ,
  s _ _ _ X _ _ X _ ,
  s _ X _ _ X _ _ X ,
  s _ _ X _ _ X _ _ ,

  s _ X _ X _ X _ X ,
  s _ _ X _ X _ X _ ,
  s _ X _ X _ X _ X ,
  s _ _ X _ X _ X _ ,
  s _ X _ X _ X _ X ,

  s _ X X _ X X X X ,
  s _ _ X X X X _ X ,
  s _ X X X _ X X X ,
  s _ X _ X X X X _ ,
  s _ X X X X _ X X ,

  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ X X X X X X X ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ X X X X _ _ X ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ X X X X _ _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ X ,
  s _ X X X X _ _ X ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ X X X X _ _ X ,

  s _ _ X X X X X _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ X ,
  s _ _ X X X X X _ ,

  s _ _ _ X _ X _ _ ,
  s _ X X X _ X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ X X X _ X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X X X _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X X X ,
  s _ _ _ X _ _ _ _ ,
  s _ _ _ X X X X X ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X X X _ _ ,
  s _ _ X _ _ _ X _ ,
  s _ X X _ _ _ X X ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ X _ X _ X X ,
  s _ _ X _ X X _ _ ,
  s _ X X X X _ _ _ ,
  s _ _ X _ X X _ _ ,
  s _ _ X _ X _ X X ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X X _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ X X X X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ X ,
  s _ X X X X _ _ _ ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X X _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X X _ ,
  s _ X X X X _ _ X ,

  s _ X X X X _ _ _ ,
  s _ _ _ X _ X X _ ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ X X _ ,
  s _ X X X X _ _ X ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ X X X X X ,
  s _ _ _ X _ _ _ _ ,
  s _ _ _ X _ X X X ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X _ X _ _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X X X ,
  s _ _ _ X _ _ _ _ ,
  s _ _ _ X _ X X X ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ X X X _ X _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ X X X _ X _ _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X _ X X X ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,
  s _ _ _ X _ X _ _ ,

  s _ _ _ X _ X _ _ ,
  s _ X X X _ X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X _ X X X ,
  s _ _ _ X _ X _ _ ,

  s _ X _ X X X _ X ,
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ _ X _ _ _ X _ ,
  s _ X _ X X X _ X ,

  s _ _ X X _ _ _ _ ,
  s _ X _ _ X _ _ X ,
  s _ X _ _ X _ X X ,
  s _ X _ _ X _ X _ ,
  s _ _ X X X X X _ ,

  s _ X _ _ X _ _ X ,
  s _ X X X X X X X ,
  s _ X _ _ X _ _ X ,
  s _ _ X _ _ _ X _ ,
  s _ _ _ X X X _ _ ,

  s _ X X X X X X _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ X ,
  s _ X _ _ _ X X _ ,

  s _ X X X X X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ _ _ X _ _ ,

  s _ X X X X X _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X X _ ,
  s _ X _ _ _ X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X X X X X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ X X X X _ _ ,
  s _ X _ _ _ _ X X ,
  s _ X _ _ _ _ X _ ,
  s _ X _ _ _ _ X X ,
  s _ _ X X X X _ _ ,

  s _ _ _ _ _ X _ _ ,
  s _ X _ _ X _ X _ ,
  s _ X X X X _ X _ ,
  s _ X _ _ X _ X _ ,
  s _ _ _ _ _ X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ X _ X _ ,
  s _ X X X X _ _ _ ,
  s _ X _ _ X _ X _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X X X X X X X ,
  s _ X X X X X X X ,
  s _ X X X X X X X ,
  s _ X X X X X X X ,
  s _ X X X X X X X ,

  s _ X X X _ _ _ _ ,
  s _ X X X _ _ _ _ ,
  s _ X X X _ _ _ _ ,
  s _ X X X _ _ _ _ ,
  s _ X X X _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ X X X _ X X X ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ X _ X _ ,
  s _ X X X X X _ _ ,
  s _ X _ _ X _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ X X X X ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ X X X X ,
  s _ _ _ _ X X X X ,

  s _ _ _ X _ _ X _ ,
  s _ _ X _ X _ _ X ,
  s _ X _ _ _ X _ _ ,
  s _ _ X _ X _ _ _ ,
  s _ _ _ X _ _ _ _ ,

  s _ X X X X X X _ ,
  s _ _ _ _ _ X _ X ,
  s _ _ _ _ _ X _ X ,
  s _ X _ _ X _ X _ ,
  s _ _ X X _ _ _ _ ,

  s _ _ _ X _ _ X _ ,
  s _ _ X _ X _ _ X ,
  s _ X _ _ _ X _ X ,
  s _ _ X _ X _ _ X ,
  s _ _ _ X _ _ X _ ,

  s _ _ _ X _ _ _ _ ,
  s _ _ X _ X _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ _ X _ X _ _ X ,
  s _ _ _ X _ _ X _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X X X X _ _ _ ,

  s _ _ X _ _ _ _ _ ,
  s _ X _ X _ X _ _ ,
  s _ X _ X _ X _ X ,
  s _ X _ X _ X _ _ ,
  s _ X X X X _ _ _ ,

  s _ X _ _ _ _ _ _ ,
  s _ _ X X X X _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ _ _ X X X _ _ ,

  s _ X _ _ _ _ _ X ,
  s _ X X X X X X X ,
  s _ _ X _ _ X _ _ ,
  s _ _ X _ _ X _ _ ,
  s _ _ _ X X _ _ _ ,

  s _ _ X _ _ _ _ X ,
  s _ _ X X X X X X ,
  s _ _ _ _ X _ X _ ,
  s _ _ _ _ X _ X _ ,
  s _ _ _ _ _ X _ _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ _ X X X _ _ _ ,

  s _ _ X X X _ X _ ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ X _ _ _ _ _ X ,
  s _ _ X X X _ X _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ _ X _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ _ X X X _ _ _ ,

  s _ _ _ _ X X _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ X _ ,
  s _ X _ X _ _ _ X ,
  s _ _ X X X X _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ X X _ _ _ ,
  s _ X X X _ _ _ _ ,
  s _ X _ X X _ X _ ,
  s _ _ _ _ _ _ _ X ,

  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,
  s _ _ _ _ _ _ _ X ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ _ _ X ,

  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ X _ _ _ ,

  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,
  s _ X _ X X X X X ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ _ ,

  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ X _ X _ _ _ _ ,

  s _ _ _ X _ X _ X ,
  s _ _ X X _ X _ X ,
  s _ _ X X X _ X _ ,
  s _ _ X _ X _ _ _ ,
  s _ X X X _ X _ _ ,

  s _ _ _ _ _ X X _ ,
  s _ _ _ _ X _ _ X ,
  s _ X X X X X X X ,
  s _ _ _ _ _ _ _ X ,
  s _ X X X X X X X ,

  s _ _ X _ _ _ X _ ,
  s _ X _ _ X X _ X ,
  s _ X _ X _ X _ X ,
  s _ X _ X X _ _ X ,
  s _ _ X _ _ _ X _ ,

  s _ _ X X X _ _ _ ,
  s _ X _ _ _ X _ X ,
  s _ X _ _ _ X _ _ ,
  s _ X _ _ _ X _ X ,
  s _ _ X X X _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ X _ _ _ _ _ _ ,
  s _ X _ X _ _ _ _ ,
  s _ _ X _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ X _ ,
  s _ _ _ _ _ X _ X ,
  s _ _ _ _ _ X _ X ,
  s _ _ _ _ _ _ X _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ X _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ X _ _ _ ,
  s _ _ _ _ _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ X _ _ X _ ,
  s _ _ _ X X X X X ,
  s _ _ _ X _ _ _ _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ X _ _ _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ _ X _ X _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ X _ _ X _ ,
  s _ _ _ X X _ _ X ,
  s _ _ _ X _ X _ X ,
  s _ _ _ X _ _ X _ ,
  s _ _ _ _ _ _ _ _ ,

  s _ _ _ _ _ _ _ _ ,
  s _ _ _ X X X _ _ ,
  s _ _ _ X X X _ _ ,
  s _ _ _ X X X _ _ ,
  s _ _ _ _ _ _ _ _ 
};
